spring:

  application:
    name: mslog

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:mslog;NON_KEYWORDS=USER
    user: SA
    password: 1234
    dirver-class-name: org.h2.Driver

  h2.console:
    enabled: true

  jpa:
    defer-datasource-initialization: true

    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10

mskym:
  jwt-key: "G18PvEwX4D+LwWhT+RnrPV9D7Gw6M79fRL66Pyz8KRBC0ssrOyGfcntD/kmPRATNNJCvDuoj2l0q9RCdgU65kg=="
